### ISSUE TITLE
Font discrepancy between arXiv and pdfTeX

### ISSUE THREAD

**Issue by toumix** [Compositionality/latex-template#10]
The arXiv compiler seems to use a different, larger font than pdfTeX for the same code with the compositionalityarticle class, which adds up to a big difference between the two documents.

Here's a screenshot of the arXiv version:
![arXiv screenshot](https://user-images.githubusercontent.com/6673255/60961122-b8afaf80-a30b-11e9-8245-189cf3fe90b8.png)

versus the pdfTeX Version 3.14159265-2.6-1.40.19 (TeX Live 2018)
![pdfTeX screenshot](https://user-images.githubusercontent.com/6673255/60961113-b51c2880-a30b-11e9-857f-ba07039f3407.png)

Ideally I'd like the arXiv version version to look the same as the one I compiled myself, would there be a quick fix for that? Enforcing font settings one way or another?

**Comment by n-otter** [comment]
This should now be fixed in v2.
