### ISSUE TITLE
On how to use the repository "Compositionality/issues"

### ISSUE THREAD

**Issue by mroman42** [Compositionality/latex-template#12]
Is there any reason there exists a separate repository called `compositionality/issues` containing just issues? This is a bit confusing for me (should I try to move now the issues there? what happens with the issues people detailed here?) and I guess it is for other people, as the current repository has 9 issues and the other has none.

Would it be possible to have all issues under the same repository? Would it be possible to close the second repository, as it has not been used yet?

**Comment by n-otter** [comment]
I have now deleted the `compositionality/issues` repository, thanks for pointing this out!
