### ISSUE TITLE
amsthm package conflicts with compositionalityarticle.cls

### ISSUE THREAD

**Issue by johncarlosbaez** [Compositionality/latex-template#19]
To get \begin{thm} and \end{thm} to work I usually use \amsthm.   But it doesn't work along with compositionalityarticle.cls, apparently because both separately define a command \openbox. 

To solve this problem I'm using a hack, but it would be good to make \amsthm compatible with compositionalityarticle.cls.

Here's my hack: in the LaTeX file of my manuscript I'm not using \amsthm.  I' using a snippet taken from \amsthm, where I've changed the command \openbox to something else: \oopenbox:

`\makeatletter
\DeclareRobustCommand{\qed}{%
  \ifmmode % if math mode, assume display: omit penalty etc.
  \else \leavevmode\unskip\penalty9999 \hbox{}\nobreak\hfill
  \fi
  \quad\hbox{\qedsymbol}}
\newcommand{\oopenbox}{\leavevmode
  \hbox to.77778em{%
  \hfil\vrule
  \vbox to.675em{\hrule width.6em\vfil\hrule}%
  \vrule\hfil}}
\newcommand{\qedsymbol}{\oopenbox}
\newenvironment{proof}[1][\proofname]{\par
  \normalfont
  \topsep6\p@\@plus6\p@ \trivlist
  \item[\hskip\labelsep\itshape
    #1.]\ignorespaces
}{%
  \qed\endtrivlist
}
\newcommand{\proofname}{Proof}
\makeatother`

**Comment by tetrapharmakon** [comment]
Apparently the problem was caused by a bad behaviour of `txfonts` together with some other package.
