### ISSUE TITLE
Italics in lmr font not working

### ISSUE THREAD

**Issue by jvdwetering** [Compositionality/latex-template#3]
Consider the following MWE:

```
\documentclass[a4paper,superscriptaddress,11pt,unpublished]{compositionalityarticle}
\pdfoutput=1
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

\usepackage{amsthm}
\newtheorem{theorem}{Theorem}

\begin{document}

\begin{theorem}
  Some \emph{emphasized} text.
\end{theorem}

\end{document}
```

The emphasized text is not italicised and the output gives the following warning:
```c:\texlive\2016\texmf-dist\tex\latex\pgf\basiclayer\pgf.sty:14: LaTeX Font Warning: Font shape `T1/lmr/l/it' undefined(Font)              using `T1/lmr/l/n' instead on input line 14.```

**Comment by n-otter** [comment]
I tested the MWE, ad this is now solved with v2
