### ISSUE TITLE
Font size of subsection headings

### ISSUE THREAD

**Issue by svenkeidel** [Compositionality/latex-template#4]
Hello,

I followed the design guide of the latex template and set the font size to `11pt`. With this setting, subsection headings appear smaller than the text itself. 

![2019-01-18-095153_726x156_scrot](https://user-images.githubusercontent.com/266500/51375644-b875ea80-1b06-11e9-94e7-2f7ddd328df5.png)

This does not look right.

Regards,
Sven

**Comment by n-otter** [comment]
Please provide a MWE, we cannot help you otherwise.

**Comment by n-otter** [comment]
this is fixed in v2
