### ISSUE TITLE
Inclusion of amsthm breaks font size in theorem environments

### ISSUE THREAD

**Issue by zamdzhiev** [Compositionality/latex-template#5]
If I simply put `\usepackage{amsthm}` in the template .tex file you have provided, then this changes how text is formatted in theorem environments to be inconsistent with the rest of the document. The font size becomes smaller. See attached picture.
![font](https://user-images.githubusercontent.com/3357005/55075394-2c96b680-5093-11e9-9dbb-084e70c00dea.png)

**Comment by n-otter** [comment]
this is fixed in v2
