### ISSUE TITLE
ORCID iD ignored

### ISSUE THREAD

**Issue by wetneb** [Compositionality/latex-template#6]
It's great that there is an `\orcid{}` command to add ORCID ids of authors. However, it does not seem to do anything at the moment: the ORCID id is not displayed at all, and does not seem to be included in the article metadata either, unless I am missing something.

One way to add it would be to follow the widespread convention of adding a small ORCID logo next to the author with a link to the ORCID profile.

**Comment by wetneb** [comment]
See the display guidelines here: https://orcid.org/blog/2017/05/10/new-id-display-guidelines-journals-now-released

**Comment by wetneb** [comment]
Actually it there is already a hypertext link to the ORCID profile. It would be more noticeable with an ORCID logo though.

**Comment by mroman42** [comment]
Dear Antonin, 

Thank you for pointing this out. With #14 , the ORCiD logo and URI for each author now appear next to the author acknowledgements. They are not yet hyperlinked (#24) as the name of the author is. I will close this issue (the ORCiD is not ignored anymore), but please feel free to add anything else that you notice is missing and we can reopen it or start a new issue.

Thanks again!
