### ISSUE TITLE
Citations unreadable in [unpublished] mode

### ISSUE THREAD

**Issue by wetneb** [Compositionality/latex-template#7]
In unpublished mode, citations are rendered like this:
![image](https://user-images.githubusercontent.com/309908/57295565-b8542780-70c2-11e9-90b3-7987cff5ad32.png)

This bright green is way too bright for a white background, I would say.

**Comment by wetneb** [comment]
This can be "solved" using `\usepackage[allcolors=mutedcoral]{hyperref}`.

**Comment by n-otter** [comment]
This is fixed in v2.
